services:
    monorepo:
        build:
            context: .
            dockerfile: docker/DEV.Dockerfile
        volumes:
            - ./:/app/
        ports:
            - "8000:8000"
            - "8001:8001"
        networks:
            - microservices

networks:
    microservices:
        driver: bridge
